# Generated by Django 4.0 on 2022-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_restaurant', '0003_order_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='item_serial_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
