# Generated by Django 4.0 on 2022-11-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_restaurant', '0007_category_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='fortran', max_length=100),
            preserve_default=False,
        ),
    ]
