# Generated by Django 4.0 on 2022-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_restaurant', '0009_item_contains_egg'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_link',
            field=models.CharField(default='nothign', max_length=100),
            preserve_default=False,
        ),
    ]
