# Generated by Django 4.0 on 2022-11-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_restaurant', '0010_item_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.CharField(max_length=1000),
        ),
    ]
