# Generated by Django 4.0 on 2022-11-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_restaurant', '0013_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquantity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
